import { test as base, expect } from "@playwright/test";
import fs from "fs";

// Read OIDC session data generated by global-setup
let sessionAuth = null;
try {
  const jsonPath = new URL("../session-auth.json", import.meta.url);
  const raw = fs.readFileSync(jsonPath, "utf-8");
  sessionAuth = JSON.parse(raw);
} catch (err) {
  // eslint-disable-next-line no-console
  console.warn("[auth.fixture] session-auth.json not found or invalid, running without session injection.", err);
}

const test = base.extend({
  page: async ({ page }, use) => {
    // In localhost mode there is no OIDC session to inject — skip it entirely.
    if (process.env.LOCALHOST_RUN !== "true" && sessionAuth?.key && sessionAuth?.value) {
      await page.addInitScript(({ key, value }) => {
        try {
          const v = typeof value === "string" ? value : JSON.stringify(value);
          window.sessionStorage.setItem(key, v);
        } catch (e) {
          // eslint-disable-next-line no-console
          console.error("[auth.fixture] Failed to set sessionStorage auth", e);
        }
      }, { key: sessionAuth.key, value: sessionAuth.value });
    }

    // Enforce 100% zoom for all test pages
    await page.addInitScript(() => {
      try { document.documentElement.style.zoom = '100%'; } catch (e) {}
    });

    await use(page);
  },
});

export { test, expect };


